test_that("v02 batch and progressive results agree with synchronous results", {
  cfg <- v02_test_config(); v02_forbid_http(); v02_prepare_cep(cfg, v02_fixtures)
  origins <- read_origin_file(file.path(v02_fixtures, "origins.csv"))
  eq <- v02_destinations(v02_fixtures)
  graphs <- list(motorcar = v02_graph(v02_fixtures))
  parameters <- list(modes = "motorcar", directions = "both")
  expected <- calculate_proximity(resolve_origins(origins, cfg)$valid, eq, graphs,
    modes = "motorcar", directions = "both", config = cfg)
  path <- file.path(cfg$jobs_dir, "batch")
  batch <- process_batch(origins, path, eq, graphs, cfg, parameters)
  expected_summary <- jsonlite::read_json(file.path(v02_fixtures, "expected", "batch.json"), simplifyVector = TRUE)
  expect_equal(batch$summary[names(expected_summary)], expected_summary)
  parts <- list.files(file.path(path, "partitions"), full.names = TRUE)
  actual <- dplyr::bind_rows(lapply(parts, function(p) as.data.frame(arrow::read_parquet(p))))
  expect_equal(v02_projection(actual), v02_projection(expected), tolerance = 1e-8)
  before <- file.info(parts)$mtime
  resumed <- process_batch(origins, path, eq, graphs, cfg, parameters)
  expect_equal(file.info(parts)$mtime, before)
  expect_equal(resumed$errors$query_id, batch$errors$query_id)
  expect_error(process_batch(origins, path, eq, graphs, cfg, list(k = 3)), "parâmetros mudaram")
  duplicate <- origins[c(1, 2, 1), ]; duplicate$query_id <- c("same", "good", "same")
  bad <- process_batch(duplicate, file.path(cfg$jobs_dir, "duplicate"), eq, graphs, cfg, parameters)
  expect_equal(sort(bad$errors$input_row), c(1L, 3L))

  pool <- new_web_pool()
  id <- web_submit(pool, origins, eq, graphs, cfg, "motorcar", "both", "batch")
  job <- pool$jobs[[id]]$dir
  web_job_worker(file.path(job, "request.rds"))
  state <- web_job_read(job)
  expect_equal(state$status, "completed")
  expect_equal(state$completed_units, 4L)
  expect_equal(sort(state$errors$query_id), c("invalid", "missing"))
  expect_equal(v02_projection(web_job_results(job)), v02_projection(expected), tolerance = 1e-8)
  expect_equal(v02_diagnostics(web_job_results(job)), v02_diagnostics(expected))
  expect_true(all(readRDS(file.path(job, state$parts[1]))$distance_family == "geometric"))
  export <- web_batch_bundle(job, state)
  zipfile <- file.path(cfg$jobs_dir, "fixture.zip")
  zip::zipr(zipfile, list.files(export), root = export, include_directories = FALSE)
  names <- utils::unzip(zipfile, list = TRUE)$Name
  expect_true(all(c("results.csv", "manifest.json", "errors.csv") %in% names))
  expect_false(any(grepl("request|worker|input\\.", names)))
  exported <- readr::read_csv(file.path(export, "results.csv"), show_col_types = FALSE)
  expect_true(all(exported$analysis_status == "completed"))
  expect_equal(nrow(exported), nrow(expected))
})

test_that("v02 missing graph keeps geometric parts and queued cancellation launches nothing", {
  cfg <- v02_test_config(); v02_forbid_http()
  pool <- new_web_pool(function(...) stop("must not launch"))
  id <- web_submit(pool, v02_origin(v02_fixtures), v02_destinations(v02_fixtures), NULL,
    cfg, "motorcar", "both", "single")
  job <- pool$jobs[[id]]$dir
  web_job_worker(file.path(job, "request.rds"))
  state <- web_job_read(job)
  expect_equal(state$status, "failed")
  expect_equal(state$completed_units, 1)
  expect_equal(state$total_units, 2)
  result <- web_job_results(job)
  expect_setequal(unique(result$distance_family), "geometric")
  expect_true(all(web_export_results(result, state)$analysis_status == "failed"))
  expect_false(jsonlite::read_json(file.path(web_batch_bundle(job, state), "manifest.json"))$complete)
  id2 <- web_submit(pool, v02_origin(v02_fixtures), v02_destinations(v02_fixtures), list(),
    cfg, character(), "both", "single")
  web_stop(pool, id2); web_poll(pool)
  expect_equal(web_job_read(pool$jobs[[id2]]$dir)$status, "cancelled")
  expect_null(pool$jobs[[id2]]$process)
})

test_that("v02 installed or source worker completes the synthetic network in a child", {
  cfg <- v02_test_config()
  pool <- new_web_pool()
  id <- web_submit(pool, v02_origin(v02_fixtures), v02_destinations(v02_fixtures),
    list(motorcar = v02_graph(v02_fixtures)), cfg, "motorcar", "both", "single")
  withr::defer(web_stop(pool, id))
  web_poll(pool)
  pool$jobs[[id]]$process$wait(30000)
  expect_false(pool$jobs[[id]]$process$is_alive())
  web_poll(pool)
  state <- web_job_read(pool$jobs[[id]]$dir)
  expect_equal(state$status, "completed")
  expect_equal(state$completed_units, 2L)
  expect_equal(length(unique(web_job_results(pool$jobs[[id]]$dir)$metric_id)), 7L)
})
