test_that("offline analysis rejects known HTTP entrypoints and missing prepared inputs", {
  cfg <- v02_test_config(); v02_forbid_http(); v02_prepare_cep(cfg, v02_fixtures)
  expect_error(perform_request("https://example.invalid", cfg), "NETWORK FORBIDDEN")
  expect_error(httr2::req_perform(httr2::request("https://example.invalid")), "NETWORK FORBIDDEN")
  origin <- resolve_origins(data.frame(cep = "00000-042"), cfg)
  expect_equal(nrow(origin$valid), 1L)
  expect_equal(origin$valid$geocode_source, "Synthetic fixture only")
  x <- calculate_proximity(origin$valid, v02_records(v02_fixtures), modes = character(), config = cfg)
  expect_true(nrow(x) > 0)
  expect_true(all(x$origin_cep == "00000042"))
  expect_error(geocode_cep("00000043", cfg), "índice local")
  expect_error(load_equipment_data(cfg), "Nenhum snapshot")
  expect_length(load_network_graphs(cfg), 0L)
  expect_s3_class(create_interactive_map(x), "leaflet")
  expect_s3_class(create_static_map(x), "ggplot")
})
