test_that("v02 controlled records protect normalization, classification and identity", {
  cfg <- v02_test_config(); v02_forbid_http()
  raw_path <- file.path(v02_fixtures, "raw", "base-completa-sampa-rural.json")
  raw <- normalize_sampa_json(raw_path, "synthetic-v02")
  expect_equal(nrow(raw), 8L)
  expect_identical(raw$equipment_id[1], raw$equipment_id[8])
  expect_false(raw$equipment_id[1] == raw$equipment_id[2])
  expect_identical(raw$source_key[1], raw$source_key[2])
  later <- normalize_sampa_json(raw_path, "synthetic-later")
  expect_identical(raw$equipment_id, later$equipment_id)
  expect_true(all(raw$record_version_id != later$record_version_id))
  changed <- normalize_sampa_json(file.path(v02_fixtures, "raw", "alterado.json"), "synthetic-v02")
  expect_false(changed$equipment_id == raw$equipment_id[1])
  expect_false(any(c("email", "phone", "Email", "Telefone") %in% names(raw)))
  expect_match(raw$source_payload[1], "alfa@example.invalid", fixed = TRUE)
  expect_equal(raw$subcategory[1], "Horta | Ensino")
  checked <- validate_equipment(v02_records(v02_fixtures), cfg)
  expected <- readr::read_csv(file.path(v02_fixtures, "expected", "records.csv"),
    show_col_types = FALSE, progress = FALSE)
  expect_equal(as.data.frame(checked$data[, names(expected)]), as.data.frame(expected), tolerance = 1e-8)
  expect_equal(nrow(checked$data), 7L)
  expect_equal(nrow(checked$eligible), 3L)
  expect_setequal(checked$quarantine$coordinate_status,
    c("missing_coordinate", "incomplete_coordinate", "invalid_coordinate", "outside_study_area"))
  expect_true(all(c("feiras_organicas", "abastecimento", "organicos") %in%
    strsplit(checked$data$groups[7], "|", fixed = TRUE)[[1]]))
  expect_equal(checked$data$accessibility[1:3], c("Informada: sim", "Informada: não", "Não informada"))
  expect_equal(nrow(normalize_sampa_json(file.path(v02_fixtures, "raw", "vazio.json"))), 0)
})

test_that("v02 overlapping and empty reports preserve the complete baseline", {
  cfg <- v02_test_config(); v02_forbid_http()
  paths <- file.path(v02_fixtures, "raw", c("base-completa-sampa-rural.json", "tematico.json", "vazio.json"))
  manifest <- data.frame(path = paths, format = "json", dataset = c("base", "tematico", "vazio"))
  out <- suppressMessages(prepare_equipment_data(manifest, cfg))
  expect_equal(nrow(out), 7)
  expect_equal(nrow(validate_equipment(out, cfg)$eligible), 3)
  expect_match(out$source_reports[1], "tematico.json", fixed = TRUE)
  expect_true(is.finite(out$latitude[1]))
  expect_false(any(c("source_payload", "description", "Email", "Telefone") %in% names(out)))
  exported <- as.data.frame(arrow::read_parquet(file.path(cfg$data_dir, "processed", "equipment.parquet")))
  expect_equal(exported, out)
  expect_identical(out$equipment_id, v02_records(v02_fixtures)$equipment_id)
})
